name: Master CD

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set Maven Release version
        run: mvn versions:set -DremoveSnapshot=true -DgenerateBackupPoms=false

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Commit and Push files for Release
        run: |
          git config --local user.email "richygreat@gmail.com"
          git config --local user.name "Richy Great"
          git add -A
          git commit -m "Release Versioned"
          git push origin main --force

      - name: Set Maven Release version
        run: mvn versions:set -DnextSnapshot=true -DgenerateBackupPoms=false

      - name: Commit and Push files for Next Snapshot
        run: |
          git add -A
          git commit -m "Snapshot Versioned"
          git push origin main --force
