name: Master CD

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set Maven Major Release version
        if: contains(github.head_ref, 'MAJOR')
        run: mvn -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.nextMajorVersion}.0.0 versions:commit

      - name: Set Maven Minor Release version
        if: contains(github.head_ref, 'MINOR')
        run: mvn -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0 versions:commit

      - name: Set Maven Hotfix Release version
        if: (!contains(github.head_ref, 'MAJOR') && !contains(github.head_ref, 'MINOR'))
        run: mvn -B versions:set -DremoveSnapshot=true versions:commit

      - name: Get release version
        env:
          RELEASE_VERSION: "0.0.0"
        run: mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout >> $RELEASE_VERSION

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Commit and Push files for Release
        run: |
          git config --local user.email "richygreat@gmail.com"
          git config --local user.name "Richy Great"
          git add -A
          git commit -m "Release Versioned $RELEASE_VERSION"
          git push origin main --force

      - name: Set Maven Release version
        run: mvn -B versions:set -DnextSnapshot=true versions:commit

      - name: Commit and Push files for Next Snapshot
        run: |
          git add -A
          git commit -m "Snapshot Versioned"
          git push origin main --force
